## Lane Detection on video

In [2]:
import matplotlib.pylab as plt
import cv2
import numpy as np

In [3]:
# finds the region of interest

def region_of_interest(img, vertices):
    mask = np.zeros_like(img)
    #channel_count = img.shape[2]
    match_mask_color = 255
    cv2.fillPoly(mask, vertices, match_mask_color)
    masked_image = cv2.bitwise_and(img, mask)
    return masked_image


In [4]:
# finds the convert each frames of video into cropped image after performing canny edge detection
def process(image):
    #print(image.shape)
    if image.any() !=None:
        
        height = image.shape[0]
        width = image.shape[1]
        region_of_interest_vertices = [
            (0,height),
            (width/2,height/2 + 40),
            (width, height)
        ]
        gray_image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
        canny_image = cv2.Canny(gray_image, 120, 120)
        cropped_image = region_of_interest(canny_image,
                        np.array([region_of_interest_vertices], np.int32),)
        
        
        hough_transform(cropped_image)

    
    
    
    return cropped_image


### Apply Hough transform and print detected lines

In [5]:
# apply hough trabsform and print the lines

def hough_transform(image):
    lines = cv2.HoughLinesP(image,
                            rho=2,
                            theta=np.pi/180,
                            threshold=50,
                            lines=np.array([]),
                            minLineLength=40,
                            maxLineGap=100)
    
    
    
    print(lines)
    

In [6]:
# input the video and send each frame to function process
cap = cv2.VideoCapture('solidWhiteRight.mp4')

while cap.isOpened():
    ret, frame = cap.read()
    frame = process(frame)
    cv2.imshow('frame', frame)
    if cv2.waitKey(45) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()


[[[526 332 870 538]]

 [[678 431 850 539]]

 [[200 515 459 320]]

 [[249 467 455 322]]

 [[596 379 663 420]]

 [[504 321 576 365]]

 [[713 454 849 539]]

 [[533 335 698 434]]

 [[199 515 279 457]]

 [[187 513 430 337]]

 [[651 414 703 446]]

 [[237 489 442 329]]

 [[488 314 633 401]]]
[[[522 330 868 538]]

 [[504 321 697 442]]

 [[168 539 459 320]]

 [[150 539 388 367]]

 [[747 476 848 539]]

 [[613 383 744 474]]

 [[233 478 455 322]]

 [[643 409 692 439]]

 [[205 500 413 349]]

 [[170 539 399 360]]

 [[386 374 450 324]]

 [[757 481 822 524]]

 [[529 333 740 460]]

 [[701 446 743 472]]

 [[246 482 441 330]]]
[[[520 329 869 539]]

 [[506 323 764 485]]

 [[238 486 454 323]]

 [[587 368 651 407]]

 [[149 539 464 318]]

 [[205 513 434 335]]

 [[653 407 808 515]]

 [[673 420 734 456]]

 [[168 539 455 323]]

 [[742 472 849 539]]

 [[604 384 749 465]]

 [[503 321 548 348]]

 [[235 476 454 322]]

 [[191 508 233 479]]

 [[526 332 577 363]]

 [[479 310 599 380]]

 [[524 331 827 527]]]
[[[503 321

[[[516 327 772 499]]

 [[535 336 693 438]]

 [[676 426 782 494]]

 [[756 488 822 530]]

 [[305 425 448 325]]

 [[770 486 854 537]]

 [[310 426 479 312]]

 [[711 457 834 539]]

 [[510 324 695 448]]

 [[306 427 477 312]]

 [[305 426 454 322]]

 [[529 335 855 539]]

 [[307 427 478 312]]]
[[[508 323 853 538]]

 [[624 401 835 539]]

 [[537 337 703 444]]

 [[791 499 855 538]]

 [[531 334 617 396]]

 [[284 440 450 324]]

 [[514 326 719 464]]

 [[298 440 454 322]]

 [[760 491 833 539]]

 [[560 352 620 392]]

 [[711 448 783 494]]]
[[[510 324 855 539]]

 [[751 484 833 539]]

 [[680 437 744 481]]

 [[564 354 615 389]]

 [[531 336 645 415]]

 [[351 400 456 321]]

 [[556 349 678 437]]

 [[259 460 439 330]]

 [[529 333 655 414]]

 [[273 458 448 326]]

 [[545 347 695 438]]

 [[516 327 767 496]]]
[[[520 329 855 538]]

 [[518 328 813 526]]

 [[221 482 437 331]]

 [[242 481 450 324]]

 [[777 491 856 539]]

 [[550 345 671 432]]

 [[736 474 833 539]]

 [[537 337 712 450]]

 [[725 458 792 499]]

 [[330 407

[[[501 320 658 422]]

 [[497 318 812 538]]

 [[708 455 813 525]]

 [[313 418 442 328]]

 [[481 313 697 448]]

 [[302 417 456 321]]

 [[507 324 831 535]]

 [[789 508 836 539]]

 [[680 438 730 470]]]
[[[497 318 811 538]]

 [[653 419 792 512]]

 [[517 329 621 399]]

 [[286 427 452 323]]

 [[315 417 430 334]]

 [[586 375 630 405]]

 [[747 481 834 539]]

 [[282 430 475 314]]

 [[292 432 440 329]]

 [[499 319 814 539]]]
[[[518 333 812 539]]

 [[499 319 702 451]]

 [[512 325 740 478]]

 [[274 445 440 329]]

 [[709 457 834 539]]

 [[257 446 438 333]]

 [[265 449 416 343]]

 [[268 448 394 357]]

 [[501 321 820 529]]]
[[[499 319 813 539]]

 [[516 327 778 503]]

 [[225 467 437 334]]

 [[514 326 702 453]]

 [[235 469 318 415]]

 [[789 509 833 539]]

 [[700 450 744 480]]

 [[236 469 454 322]]

 [[225 468 436 331]]

 [[732 471 796 515]]]
[[[544 352 811 539]]

 [[514 326 758 490]]

 [[523 333 661 426]]

 [[199 496 248 463]]

 [[203 481 436 335]]

 [[197 497 302 426]]

 [[699 451 833 539]]

 [[497 318

##  Visualisation on video

In [2]:
import matplotlib.pylab as plt
import cv2
import numpy as np

In [3]:
def region_of_interest(img, vertices):
    mask = np.zeros_like(img)
    #channel_count = img.shape[2]
    match_mask_color = 255
    cv2.fillPoly(mask, vertices, match_mask_color)
    masked_image = cv2.bitwise_and(img, mask)
    return masked_image

In [16]:
def draw_the_lines(img, lines):
    img = np.copy(img)
    blank_image = np.zeros((img.shape[0], img.shape[1], 3), dtype=np.uint8)

    for line in lines:
        for x1, y1, x2, y2 in line:
            cv2.line(blank_image, (x1,y1), (x2,y2), (0, 0, 255), thickness=6)

    img = cv2.addWeighted(img, 0.8, blank_image, 1, 0.0)
    return img

In [24]:
def process(image):
    #print(image.shape)
    height = image.shape[0]
    width = image.shape[1]
    region_of_interest_vertices = [
        (0, height),
        (width/2, height/2+40),
        (width, height)
    ]
    gray_image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
    canny_image = cv2.Canny(gray_image, 120, 120)
    cropped_image = region_of_interest(canny_image,
                    np.array([region_of_interest_vertices], np.int32),)
    lines = cv2.HoughLinesP(cropped_image,
                            rho=1,
                            theta=np.pi/180,
                            threshold=40,
                            lines=np.array([]),
                            minLineLength=40,
                            maxLineGap=120)
    image_with_lines = draw_the_lines(image, lines)
    return image_with_lines


In [25]:
cap = cv2.VideoCapture('solidWhiteRight.mp4')

while cap.isOpened():
    ret, frame = cap.read()
    frame = process(frame)
    cv2.imshow('frame', frame)
    if cv2.waitKey(60) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()